version: '3.9'
services:
  postgres:
    container_name: postgres-db
    image: postgres
    environment:
      POSTGRES_USER: ordrsmartuser
      POSTGRES_PASSWORD: ordrsmartpwd
    ports:
      - "5432:5432"
    networks:Sample_requests
      - postgres
    restart: unless-stopped

  ordrsmart-api:
    image: pkerbynn/ordrsmart-api:latest
    container_name: ordrsmart-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - postgres
    depends_on:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres_data:

